### ISSUE TITLE
Package Marathon for Debian stretch?

### ISSUE THREAD

**Issue by chriskuehl** [mesosphere/marathon-pkg#31]
[Debian stretch](https://www.debian.org/News/2017/20170617.en.html) was released yesterday and is now the new Debian "stable". Would you please consider building Marathon packages for it, in addition to the packages currently built for Debian jessie (old stable)?

**Comment by jvperrin** [comment]
Since the whole package build process appears to have been merged into the [mesosphere/marathon](https://github.com/mesosphere/marathon#building-from-source) repo, we've made a docker-based build to make Debian stretch packages at [ocf/marathon-deb](https://github.com/ocf/marathon-deb) if anyone wants to build it themself or grab the Debian packages off [our Jenkins](https://jenkins.ocf.berkeley.edu/job/marathon-deb/job/master/).

Running `sbt packageLinux` on that repo also works, but it makes rpm packages and makes packages using Upstart and System-V, which are not applicable for Debian stretch, so those are skipped in our build process since we just want the systemd Debian package.

**Comment by timcharper** [comment]
Closing in favor of https://jira.mesosphere.com/browse/MARATHON-7995
